struct AgencyProposalSegment {
    let proposalSegmentUuid: String?
    let pnr: String?
    let booked: Bool?
    let confirmationNumber: String?
    let endDate: String?
    let endTime: String?
    let startDate: String?
    let startTime: String?
    let policyCompliant: Int?
    let proposalSegmentType: String?
    let segmentTypeCode: String?
    let vendorName: String?
    let comments: String?
    let classOfService: String?
    let duration: Int?
    let startLocation: RaaSLocation?
    let endLocation: RaaSLocation?
    let mealPreference: String?
    let seatNumber: String?
    let flightNumber: String?
    let aircraft: String?
    let departureTerminal: String?
    let arrivalTerminal: String?
    let trainNumber: String?
    let wagonNumber: String?
    let startRailStation: String?
    let startRailStationName: String?
    let endRailStation: String?
    let endRailStationName: String?
    let airConditioning: Bool?
    let carEquipment: String?
    let transmissionPreference: String?
    let dropOffCollectionPhoneNumber: String?
    let startLocationDetail: String?
    let endLocationDetail: String?
    let name: String?
    let roomDescription: String?
    let providerPhone: String?
    let location: RaaSLocation?
    let locationDetail: String?
    let address: String?
    let postalCode: String?
}