struct ExpectedExpense {
    let id: String
    let key: String
    let segmentIds: [String?]?
    let type: String?
    let transactionDate: String?
    let description: String?
    let areComments: String?
    let transactionAmount: Double?
    let postedAmount: Double?
    let currencyCode: String?
    let crnKey: Int?
    let allocationState: Bool?
    let fromSegment: Bool?
    let formId: String?
    let customFormId: String?
    let expId: String?
    let formType: String?
    let allocationVersion: String?
    let expName: String?
    let approvedAmount: Double?
    let segmentStartDate: String?
    let segmentTypeId: String?
    let dailyAllowanceId: String?
    let isSelfBooked: Bool?
    let isAutoEstimatedAgencyFees: Bool?
    let fromLocation: ExpectedExpenseLocation?
    let toLocation: ExpectedExpenseLocation?
    let tripType: String?
}