struct FieldControl {
    let id: String
    let access: Access
    let ctrlType: CtrlType
    let dataType: DataType
    let required: Bool
    let purpose: String?
    let sequence: Int?
    let originalCtrlType: CtrlType?
    let maxLength: Int?
    let width: Int?
    let label: String?
    let rows: Int?
    let cols: Int?
    let listKey: Int?
    let hierKey: Int?
    let hierLevel: Int?
    let custom: String?
    let defaultValue: String?
    let defaultValueLiCode: String?
    let defaultValueLiName: String?
    let originalAccess: Access?
    let ffKey: Int?
    let ftCode: String?
    let hiddenIfEmpty: String?
    let isDynamicField: String?
    let listInfo: ListInfo?
    let listOptions: [ListItem?]?
    let isCopyDownSourceForOtherForms: Bool?
    let tooltip: String?
    let validationExpression: String?
    let failureMsg: String?
    let defaultValueLocation: DefaultValueLocation?
}